const styles = (theme) => ({
    root : {
        height         : "100%",
        width          : "100%",
        display        : "flex",
        justifyContent : "center",
        alignItems     : "center",
    },
    loader : {
        height    : theme.spacing(10),
        width     : theme.spacing(10),
        animation :
            "$loader-5-1 2s cubic-bezier(0.770, 0.000, 0.175, 1.000) infinite",
        "&::before" : {
            content      : "''",
            display      : "block",
            position     : "absolute",
            top          : 0,
            left         : 0,
            bottom       : 0,
            right        : "auto",
            margin       : "auto",
            width        : theme.spacing(2),
            height       : theme.spacing(2),
            background   : "#FFF",
            borderRadius : "50%",
            animation    :
                "$loader-5-2 2s cubic-bezier(0.770, 0.000, 0.175, 1.000) infinite",
        },
        "&::after" : {
            content      : "''",
            display      : "block",
            position     : "absolute",
            top          : 0,
            left         : "auto",
            bottom       : 0,
            right        : 0,
            margin       : "auto",
            width        : theme.spacing(2),
            height       : theme.spacing(2),
            background   : "#FFF",
            borderRadius : "50%",
            animation    :
                "$loader-5-3 2s cubic-bezier(0.770, 0.000, 0.175, 1.000) infinite",
        },
        "&>span" : {
            display  : "block",
            position : "absolute",
            top      : 0,
            left     : 0,
            bottom   : 0,
            right    : 0,
            margin   : "auto",
            height   : theme.spacing(10),
            width    : theme.spacing(10),
        },
        "&>span::before" : {
            content      : "''",
            display      : "block",
            position     : "absolute",
            top          : 0,
            left         : 0,
            bottom       : "auto",
            right        : 0,
            margin       : "auto",
            width        : theme.spacing(2),
            height       : theme.spacing(2),
            background   : "#FFF",
            borderRadius : "50%",
            animation    :
                "$loader-5-4 2s cubic-bezier(0.770, 0.000, 0.175, 1.000) infinite",
        },
        "&>span::after" : {
            content      : "''",
            display      : "block",
            position     : "absolute",
            top          : "auto",
            left         : 0,
            bottom       : 0,
            right        : 0,
            margin       : "auto",
            width        : theme.spacing(2),
            height       : theme.spacing(2),
            background   : "#FFF",
            borderRadius : "50%",
            animation    :
                "$loader-5-5 2s cubic-bezier(0.770, 0.000, 0.175, 1.000) infinite",
        },
    },
    "@keyframes loader-5-1" : {
        "0%"   : { transform: "rotate(0deg)" },
        "100%" : { transform: "rotate(360deg)" },
    },
    "@keyframes loader-5-2" : {
        "0%"   : { transform: "translate3d(0, 0, 0) scale(1); " },
        "50%"  : { transform: "translate3d(24px, 0, 0) scale(.5);" },
        "100%" : { transform: "translate3d(0, 0, 0) scale(1); " },
    },
    "@keyframes loader-5-3" : {
        "0%"   : { transform: "translate3d(0, 0, 0) scale(1);" },
        "50%"  : { transform: "translate3d(-24px, 0, 0) scale(.5);" },
        "100%" : { transform: "translate3d(0, 0, 0) scale(1);" },
    },
    "@keyframes loader-5-4" : {
        "0%"   : { transform: "translate3d(0, 0, 0) scale(1);" },
        "50%"  : { transform: "translate3d(0, 24px, 0) scale(.5);" },
        "100%" : { transform: "translate3d(0, 0, 0) scale(1);" },
    },
    "@keyframes loader-5-5" : {
        "0%"   : { transform: "translate3d(0, 0, 0) scale(1);" },
        "50%"  : { transform: "translate3d(0, -24px, 0) scale(.5);" },
        "100%" : { transform: "translate3d(0, 0, 0) scale(1);" },
    },
});

export default styles;
