module.exports = {
    YOUTUBE: "YOUTUBE",
    FILES: "FILES",
    CHATS: "CHATS",
    QUIZZES: "QUIZZES",
    BREAKOUT_ROOMS: "BREAKOUT_ROOMS",
    CLASS_DOCUMENT: "CLASS_DOCUMENT",
    WHITEBOARD: "WHITEBOARD",
    LATEX: "LATEX",
};
